import type { Product, ProductFormState, PublicSettings } from '../types/store';
import { defaultStoreThemeId } from '../storefront/catalog';

import { PRODUCT_NAME } from './platform';

export const defaultSettings: PublicSettings = {
  storeName: PRODUCT_NAME,
  storeDescription: '',
  storeUrl: 'http://localhost:5173',
  storeMode: 'hybrid',
  supportEmail: 'support@example.com',
  defaultCurrency: 'USD',
  downloadExpiryDays: '7',
  downloadLimit: '5',
  footerText: 'Thanks for visiting our store.',
  termsUrl: '',
  privacyUrl: '',
  logoPath: '',
  faviconPath: '',
  logoUrl: '',
  faviconUrl: '',
  brandPrimaryColor: '#73f0c5',
  brandSecondaryColor: '#4eb8ff',
  heroHeadline: 'Sell digital products under your own brand.',
  heroSubheadline: 'Launch a storefront that feels like yours, connect Stripe and SMTP, and start selling files directly to customers.',
  primaryCtaLabel: 'Browse products',
  secondaryCtaLabel: 'View featured product',
  homepageMode: 'hero-grid',
  featuredProductSlug: '',
  showHeroHighlights: 'false',
  catalogEyebrow: 'Available now',
  catalogTitle: 'Shop the catalog',
  catalogDescription: 'Browse published products and purchase with secure delivery.',
  emptyCatalogTitle: 'New releases coming soon',
  emptyCatalogMessage: 'This storefront is getting ready. Check back soon for the first release.',
  aboutTitle: '',
  aboutBody: '',
  announcementText: '',
  announcementUrl: '',
  socialWebsite: '',
  socialTwitter: '',
  socialInstagram: '',
  socialYoutube: '',
  showPublicAdminLinks: 'false',
  storefrontTheme: defaultStoreThemeId,
  storefrontThemeBase: defaultStoreThemeId,
  storefrontThemeStylesheetUrl: '',
  storefrontThemePackageLayout: '',
};

export const settingsFields: Array<{ key: string; label: string }> = [
  { key: 'storeName', label: 'Store name' },
  { key: 'storeDescription', label: 'Store description' },
  { key: 'storeUrl', label: 'Store URL' },
  { key: 'storeMode', label: 'Store mode' },
  { key: 'supportEmail', label: 'Support email' },
  { key: 'heroHeadline', label: 'Hero headline' },
  { key: 'heroSubheadline', label: 'Hero subheadline' },
  { key: 'primaryCtaLabel', label: 'Primary CTA label' },
  { key: 'secondaryCtaLabel', label: 'Secondary CTA label' },
  { key: 'brandPrimaryColor', label: 'Primary brand color' },
  { key: 'brandSecondaryColor', label: 'Secondary brand color' },
  { key: 'homepageMode', label: 'Homepage mode' },
  { key: 'featuredProductSlug', label: 'Featured product' },
  { key: 'showHeroHighlights', label: 'Show hero highlight cards' },
  { key: 'catalogEyebrow', label: 'Catalog eyebrow' },
  { key: 'catalogTitle', label: 'Catalog title' },
  { key: 'catalogDescription', label: 'Catalog description' },
  { key: 'emptyCatalogTitle', label: 'Empty catalog title' },
  { key: 'emptyCatalogMessage', label: 'Empty catalog message' },
  { key: 'aboutTitle', label: 'About section title' },
  { key: 'aboutBody', label: 'About section body' },
  { key: 'announcementText', label: 'Announcement text' },
  { key: 'announcementUrl', label: 'Announcement link' },
  { key: 'socialWebsite', label: 'Website URL' },
  { key: 'socialTwitter', label: 'Twitter URL' },
  { key: 'socialInstagram', label: 'Instagram URL' },
  { key: 'socialYoutube', label: 'YouTube URL' },
  { key: 'showPublicAdminLinks', label: 'Show admin links on storefront' },
  { key: 'defaultCurrency', label: 'Default currency' },
  { key: 'downloadExpiryDays', label: 'Download expiry days' },
  { key: 'downloadLimit', label: 'Download limit' },
  { key: 'footerText', label: 'Footer text' },
  { key: 'termsUrl', label: 'Terms URL' },
  { key: 'privacyUrl', label: 'Privacy URL' },
  { key: 'smtpHost', label: 'SMTP host' },
  { key: 'smtpPort', label: 'SMTP port' },
  { key: 'smtpUser', label: 'SMTP user' },
  { key: 'smtpPass', label: 'SMTP pass' },
  { key: 'smtpFrom', label: 'SMTP from' },
  { key: 'stripeSecretKey', label: 'Stripe secret key' },
  { key: 'stripePublicKey', label: 'Stripe public key' },
  { key: 'stripeWebhookSecret', label: 'Stripe webhook secret' },
  { key: 'paymentProviderMode', label: 'Payment providers' },
  { key: 'bkashAppKey', label: 'bKash app key' },
  { key: 'bkashAppSecret', label: 'bKash app secret' },
  { key: 'bkashUsername', label: 'bKash username' },
  { key: 'bkashPassword', label: 'bKash password' },
  { key: 'bkashSandbox', label: 'bKash sandbox mode' },
  { key: 'headlessApiKey', label: 'Headless API key' },
  { key: 'headlessSecretKey', label: 'Headless secret key' },
  { key: 'embedAllowedOrigins', label: 'Embed allowed origins' },
];

export const emptyProductForm = (currency: string): ProductFormState => ({
  title: '',
  slug: '',
  summary: '',
  description: '',
  tags: '',
  priceCents: '',
  currency,
  status: 'draft',
  version: '',
  changelog: '',
  seoTitle: '',
  metaDescription: '',
  featuredImage: null,
  galleryImages: [],
  digitalFile: null,
});

export const parseTagsInput = (value: string) =>
  value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);

export const productToFormState = (product: Product): ProductFormState => ({
  title: product.title,
  slug: product.slug,
  summary: product.summary,
  description: product.description,
  tags: product.tags.join(', '),
  priceCents: String(product.priceCents),
  currency: product.currency,
  status: product.status,
  version: product.version || '',
  changelog: product.changelog || '',
  seoTitle: product.seoTitle || '',
  metaDescription: product.metaDescription || '',
  featuredImage: null,
  galleryImages: [],
  digitalFile: null,
});
